services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock-standalone
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: simplifypay_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miguel
      POSTGRES_DB: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  wiremock_data: