services:

  postgres:
    image: postgres:15
    container_name: simplifypay_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miguel
      POSTGRES_DB: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
